### ISSUE TITLE
关于在我的网站中使用你的图片服务的说明

### ISSUE THREAD

**Issue by dragon-fish** [pixiv-cat/pixivcat-backend#1]
您好，我是一个开源 Pixiv 网站的作者，我曾在2024年3月5日向 contact@pixiv.cat 发送了一篇询问邮件，但截至目前未收到您的回信。

提交这篇 issue 的目的是，希望您了解我计划在我的网站中使用您的图片服务。

由于我的网站性质，导致它的产生的图片请求频次远高于个人博客等场景，因此特别向您说明此情况，以便您及时了解可能发生的负载。

供您参考的数据：

- 请求来源：https://pixiv.js.org/
- 日均请求量：~50k
- 曾达到的日请求峰值：~100k

另外，我的网站是开源项目，未有任何盈利，供您参考：https://github.com/FreeNowOrg/PixivNow

如果有任何问题或异议，请及时联系我，我将尽力配合，感激不尽。

**Comment by jongcs** [comment]
本服務歡迎開源開發者使用，但是希望能夠在頁面中註明使用了這項服務。
另外，目前在晚高峰的伺服器負載已經超過上限，可能會影響服務品質。

**Comment by dragon-fish** [comment]
https://github.com/FreeNowOrg/PixivNow/pull/128
